# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
I'm thrilled that you're considering sponsoring me and my open-source projects. I build these projects because I genuinely believe in the power of open source and love helping people.

Before you decide to sponsor, please keep in mind:

- No special treatment for sponsors: Issues and feature requests from sponsors will not be prioritized or treated differently.
- I'm not a full-time open-source developer, so it's also wonderful if you choose to donate this money to charities or people in need. However, your support is always appreciated and can even buy me a coffee!

Thank you for your generosity and support! ❤️

ko_fi: antoineross
